module.exports = {
    dataSources: {
        // aka: "aka_name",
        aka: 'aka',
        es: 'es_name',
        ads: 'ads_name',
        adNN: 'adNN_name',
        nvSQL: 'nvSQL_name',
        lmn: 'lmn_name',
        mdn: 'mdn_name',
        novaMM: 'novaMM_name',
        mm: 'mm_name',
        sf: 'sf_name',
        city: 'city_name',
        mir: 'mir_name',
    },
    dataSourcesRevert: {
        // aka: "aka_name",
        aka: 'aka',
        es_name: 'es',
        ads_name: 'ads',
        adNN_name: 'adNN',
        nvSQL_name: 'nvSQL',
        lmn_name: 'lmn',
        mdn_name: 'mdn',
        novaMM_name: 'novaMM',
        mm_name: 'mm',
        sf_name: 'sf',
        city_name: 'city',
        mir_name: 'mir',
    },
};
